org: saularanda
app: test-serverless
service: test-serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:335946760084:table/Notes

functions:
  starWarsApi:
    handler: src/handler.starWarsApi
    events:
      - http:
          method: get
          path: /personaje/{id}
  createNote:
    handler: src/handler.createNote
    events:
      - http:
          method: post
          path: /note
  getAllNotes:
    handler: src/handler.getAllNotes
    events:
      - http:
          method: get
          path: /note
  getNote:
    handler: src/handler.getNote
    events:
      - http:
          method: get
          path: /note/{id}
  updateNote:
    handler: src/handler.updateNote
    events:
      - http:
          method: put
          path: /note/{id}
resources:
  Resources:
    Notes:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Notes
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
